SET(CPP_FILES 
source/mapRegistrationAlgorithmBase.cpp
source/mapIterativeAlgorithmBase.cpp
source/mapMultiResRegistrationAlgorithmBase.cpp
source/mapAlgorithmStateChangeEvent.cpp
source/mapAlgorithmException.cpp
source/mapAlgorithmWrapperEvent.cpp
source/mapAlgorithmProfileHelper.cpp
source/mapMetaPropertyInfo.cpp
source/mapMetaPropertyAlgorithmBase.cpp
source/mapUID.cpp  
source/mapOptimizerControlInterface.cpp
source/mapOptimizerGetterInterface.cpp
source/mapStoppableAlgorithmInterface.cpp
)

SET(H_FILES 
include/mapAlgorithmEvents.h
include/mapAlgorithmException.h
include/mapAlgorithmIdentificationInterface.h
include/mapAlgorithmStateChangeEvent.h
include/mapAlgorithmWrapperEvent.h
include/mapAlgorithmProfileHelper.h
include/mapAnalyticAlgorithmInterface.h
include/mapArbitraryImagePyramidesPolicy.h
include/mapImagePyramidesGetterInterface.h
include/mapImagePyramidesSetterInterface.h
include/mapImageRegistrationAlgorithmBase.h
include/mapImageRegistrationAlgorithmInterface.h
include/mapInterimRegistrationResultAccessInterface.h
include/mapIterativeAlgorithmBase.h
include/mapIterativeAlgorithmInterface.h
include/mapIterativeRegistrationAlgorithm.h
include/mapMaskedRegistrationAlgorithmBase.h
include/mapMaskedRegistrationAlgorithmInterface.h
include/mapMetaPropertyAlgorithmBase.h
include/mapMetaPropertyAlgorithmInterface.h
include/mapMetaPropertyInfo.h
include/mapMultiResImageRegistrationAlgorithmBase.h
include/mapModifiableMultiResImageRegistrationAlgorithmBase.h
include/mapMultiResRegistrationAlgorithmBase.h
include/mapMultiResRegistrationAlgorithmInterface.h
include/mapMultiResRegistrationAlgorithmSetterInterface.h
include/mapMultiResScheduleSetterInterface.h
include/mapOptimizerControlInterface.h
include/mapOptimizerGetterInterface.h
include/mapPointSetRegistrationAlgorithmBase.h
include/mapPointSetRegistrationAlgorithmInterface.h
include/mapRegistrationAlgorithm.h
include/mapRegistrationAlgorithmBase.h
include/mapRegistrationAlgorithmInterface.h
include/mapSealedImagePyramidesPolicy.h
include/mapStoppableAlgorithmInterface.h
include/mapUID.h
include/mapMaskBoundingBoxHelper.h
boxed/mapDummyRegistrationAlgorithm.h
boxed/mapDummyImageRegistrationAlgorithm.h	
)

SET(TPP_FILES
include/mapImageRegistrationAlgorithmBase.tpp
include/mapPointSetRegistrationAlgorithmBase.tpp
include/mapMaskedRegistrationAlgorithmBase.tpp
include/mapMultiResImageRegistrationAlgorithmBase.tpp
include/mapModifiableMultiResImageRegistrationAlgorithmBase.tpp
include/mapRegistrationAlgorithm.tpp
include/mapIterativeRegistrationAlgorithm.tpp
include/mapArbitraryImagePyramidesPolicy.tpp
include/mapSealedImagePyramidesPolicy.tpp
include/mapImagePyramidesSetterInterface.tpp
include/mapImagePyramidesGetterInterface.tpp
boxed/mapDummyRegistrationAlgorithm.tpp
boxed/mapDummyImageRegistrationAlgorithm.tpp
)

SET(TEST_CPP_FILES
test/mapAlgorithmIdentificationBaseTest.cpp
test/mapAlgorithmsTests.cpp
test/mapArbitraryImagePyramidesPolicyTest.cpp
test/mapImageRegistrationAlgorithmBaseTest.cpp
test/mapIterativeAlgorithmBaseTest.cpp
test/mapIterativeRegistrationAlgorithmTest.cpp
test/mapMaskedRegistrationAlgorithmBaseTest.cpp
test/mapMetaPropertyInfoTest.cpp
test/mapMetaPropertyAlgorithmBaseTest.cpp
test/mapMultiResImagedRegistrationAlgorithmInterfaceTest.cpp
test/mapOptimizerControlInterfaceTest.cpp
test/mapRegistrationAlgorithmBaseTest.cpp
test/mapRegistrationAlgorithmTest.cpp
test/mapUIDTest.cpp 
test/mapStateTestCommand.cpp
test/mapAlgorithmProfileHelperTest.cpp
test/mapMaskBoundingBoxHelperTest.cpp
)