SET(CPP_FILES
source/mapBoostUIDPolicy.cpp
source/mapSimpleDemoInstancer.cpp
source/mapSimpleInformationEntity.cpp
source/mapSimpleInformationSpace.cpp
source/mapSimpleOntology.cpp
source/mapSimpleTransformationInfo.cpp
)

SET(H_FILES 
include/mapBoostUIDPolicy.h
include/mapSimpleAlgorithmExecutionInfo.h
include/mapSimpleDemoInstancer.h
include/mapSimpleInformationEntity.h
include/mapSimpleInformationSpace.h
include/mapSimpleOntology.h
include/mapSimpleOntologyCore.h
include/mapSimplePathSearch.h
include/mapSimpleProblemModel.h
include/mapSimpleProblemStatement.h
include/mapSimpleRegistrationInfo.h
include/mapSimpleRegistrationPath.h
include/mapSimpleRegPathCheckPolicy.h
include/mapSimpleRegPathOption.h
include/mapSimpleRegPathOptionCollection.h
include/mapSimpleSemanticCorrelation.h
include/mapSimpleTransformationInfo.h
include/mapSimpleTransformationPath.h
include/mapSimpleTransPathCheckPolicy.h
include/mapSimpleTransPathOption.h
include/mapSimpleTransPathOptionCollection.h
)

SET(TPP_FILES
include/mapSimpleOntologyCore.tpp
include/mapSimplePathSearch.tpp
include/mapSimpleRegPathCheckPolicy.tpp
include/mapSimpleTransPathCheckPolicy.tpp
)

SET(TEST_CPP_FILES
test/mapOntologySimpleTests.cpp
test/mapSimpleOntologyCoreTest.cpp
test/mapSimpleOntologyTest.cpp
test/mapSimpleProblemModelTest.cpp
test/mapSimpleProblemStatementTest.cpp
test/mapSimpleRegistrationInfoTest.cpp
test/mapSimpleRegistrationPathTest.cpp
test/mapSimpleTestHelper.cpp
test/mapSimpleTransformationInfoTest.cpp
test/mapSimpleTransformationPathTest.cpp
)