SET(TEST_DATA_ROOT ${MatchPointTesting_SOURCE_DIR}/Data)

SET(TEMP ${MatchPointTesting_BINARY_DIR}/Temporary)
SET(EXAMPLES_DATA_ROOT "${MatchPoint_SOURCE_DIR}/Examples/Data")

#-----------------------------------------------------------------------------
ADD_TEST(mapLogbookTest ${MODULE_TESTS} mapLogbookTest)
ADD_TEST(mapPMVolumeTest ${MODULE_TESTS} mapPMVolumeTest)
ADD_TEST(mapVolumeSizeTest ${MODULE_TESTS} mapVolumeSizeTest)
ADD_TEST(mapFileDispatchTest ${MODULE_TESTS} mapFileDispatchTest)
ADD_TEST(mapExceptionObjectMacrosTest ${MODULE_TESTS} mapExceptionObjectMacrosTest)
ADD_TEST(mapFieldRepresentationDescriptorTest ${MODULE_TESTS} mapFieldRepresentationDescriptorTest)
ADD_TEST(mapRegistrationBaseTest ${MODULE_TESTS} mapRegistrationBaseTest)
ADD_TEST(mapRegistrationTest ${MODULE_TESTS} mapRegistrationTest)
ADD_TEST(mapModelBasedRegistrationKernelTest ${MODULE_TESTS} mapModelBasedRegistrationKernelTest)
ADD_TEST(mapAffineMatrixDecomposerTest ${MODULE_TESTS} mapAffineMatrixDecomposerTest)
ADD_TEST(mapPreCachedFieldBasedRegistrationKernelTest ${MODULE_TESTS} mapPreCachedFieldBasedRegistrationKernelTest)
ADD_TEST(mapServiceStackTest ${MODULE_TESTS} mapServiceStackTest)
ADD_TEST(mapGenericStaticLoadPolicyTest ${MODULE_TESTS} mapGenericStaticLoadPolicyTest)
ADD_TEST(mapStaticServiceStackTest ${MODULE_TESTS} mapStaticServiceStackTest)
ADD_TEST(mapFieldGenerationFunctorTest ${MODULE_TESTS} mapFieldGenerationFunctorTest)
ADD_TEST(mapFieldGenerationFunctorTest ${MODULE_TESTS} mapFieldGenerationFunctorTest)
ADD_TEST(mapLazyFieldBasedRegistrationKernelTest ${MODULE_TESTS} mapLazyFieldBasedRegistrationKernelTest)
ADD_TEST(mapFieldByModelFunctorTest ${MODULE_TESTS} mapFieldByModelFunctorTest)
ADD_TEST(mapFieldByModelInversionFunctorTest ${MODULE_TESTS} mapFieldByModelInversionFunctorTest 40 0.1 0.1)
ADD_TEST(mapFieldByFieldInversionFunctorTest ${MODULE_TESTS} mapFieldByFieldInversionFunctorTest 40 0.1 0.1)
ADD_TEST(mapPointVectorCombinationPolicyTest ${MODULE_TESTS} mapPointVectorCombinationPolicyTest)
ADD_TEST(mapFieldByModelFieldCombinationFunctorTest ${MODULE_TESTS} mapFieldByModelFieldCombinationFunctorTest)
ADD_TEST(mapFieldCombinationFunctorInterfaceTest ${MODULE_TESTS} mapFieldCombinationFunctorInterfaceTest)
ADD_TEST(mapFieldByFieldModelCombinationFunctorTest ${MODULE_TESTS} mapFieldByFieldModelCombinationFunctorTest)
ADD_TEST(mapFieldByFieldFieldCombinationFunctorTest ${MODULE_TESTS} mapFieldByFieldFieldCombinationFunctorTest)
ADD_TEST(mapFieldByFileLoadFunctorTest ${MODULE_TESTS} mapFieldByFileLoadFunctorTest "${TEST_DATA_ROOT}/Core/mapTestField.mhd")
ADD_TEST(mapConcreteFieldBasedRegistrationKernelTest ${MODULE_TESTS} mapConcreteFieldBasedRegistrationKernelTest)
ADD_TEST(mapCombinedFieldBasedRegistrationKernelTest ${MODULE_TESTS} mapCombinedFieldBasedRegistrationKernelTest)
ADD_TEST(mapModelBasedKernelInverterTest ${MODULE_TESTS} mapModelBasedKernelInverterTest)
ADD_TEST(mapFieldBasedKernelInverterTest ${MODULE_TESTS} mapFieldBasedKernelInverterTest)
ADD_TEST(mapInverseRegistrationKernelGeneratorTest ${MODULE_TESTS} mapInverseRegistrationKernelGeneratorTest)
ADD_TEST(mapRegistrationCombinationRequestTest ${MODULE_TESTS} mapRegistrationCombinationRequestTest)
ADD_TEST(mapRegistrationKernelCombinatorBaseTest ${MODULE_TESTS} mapRegistrationKernelCombinatorBaseTest)
ADD_TEST(mapFieldFieldKernelCombinatorTest ${MODULE_TESTS} mapFieldFieldKernelCombinatorTest)
ADD_TEST(mapModelFieldKernelCombinatorTest ${MODULE_TESTS} mapModelFieldKernelCombinatorTest)
ADD_TEST(mapFieldModelKernelCombinatorTest ${MODULE_TESTS} mapFieldModelKernelCombinatorTest)
ADD_TEST(mapModelModelKernelCombinatorTest ${MODULE_TESTS} mapModelModelKernelCombinatorTest)
ADD_TEST(mapRegistrationCombinatorTest ${MODULE_TESTS} mapRegistrationCombinatorTest)
ADD_TEST(mapPointSetMappingPerformerRequestTest ${MODULE_TESTS} mapPointSetMappingPerformerRequestTest)
ADD_TEST(mapImageMappingPerformerRequestTest ${MODULE_TESTS} mapImageMappingPerformerRequestTest)
ADD_TEST(mapPointSetByModelPerformerTest ${MODULE_TESTS} mapPointSetByModelPerformerTest)
ADD_TEST(mapPointSetByFieldPerformerTest ${MODULE_TESTS} mapPointSetByFieldPerformerTest)
ADD_TEST(mapImageByModelPerformerTest ${MODULE_TESTS} mapImageByModelPerformerTest "${TEST_DATA_ROOT}/Core/mapTestImage.png" "${TEST_DATA_ROOT}/Core/mapTestImage_X15Y10.png" 0 "${TEMP}/mapImageByModelPerformerTest")
ADD_TEST(mapImageByFieldPerformerTest ${MODULE_TESTS} mapImageByFieldPerformerTest "${TEST_DATA_ROOT}/Core/mapTestImage.png" "${TEST_DATA_ROOT}/Core/mapTestImage_X15Y10.png" "${TEST_DATA_ROOT}/Core/mapImageByFieldPerformerTest_ref1.png" "${TEST_DATA_ROOT}/Core/mapImageByFieldPerformerTest_ref2.png" 0 "${TEMP}/mapImageByFieldPerformerTest")
ADD_TEST(mapMappingTaskBaseTest ${MODULE_TESTS} mapMappingTaskBaseTest)
ADD_TEST(mapPointSetMappingTaskTest ${MODULE_TESTS} mapPointSetMappingTaskTest)
ADD_TEST(mapImageMappingTaskTest ${MODULE_TESTS} mapImageMappingTaskTest)
ADD_TEST(mapMappingTaskBatchTest ${MODULE_TESTS} mapMappingTaskBatchTest)
ADD_TEST(mapMetaPropertyTest ${MODULE_TESTS} mapMetaPropertyTest)
ADD_TEST(mapSmartMetaPropertyTest ${MODULE_TESTS} mapSmartMetaPropertyTest)
ADD_TEST(mapMetaPropertyAccessInterfaceTest ${MODULE_TESTS} mapMetaPropertyAccessInterfaceTest)
ADD_TEST(mapMetaPropertyAccessorTest ${MODULE_TESTS} mapMetaPropertyAccessorTest)
ADD_TEST(mapSDElementTest ${MODULE_TESTS} mapSDElementTest)
ADD_TEST(mapSDXMLStrReaderTest ${MODULE_TESTS} mapSDXMLStrReaderTest)
ADD_TEST(mapSDXMLFileReaderTest ${MODULE_TESTS} mapSDXMLFileReaderTest ${TEST_DATA_ROOT}/Core)
ADD_TEST(mapSDXMLStrWriterTest ${MODULE_TESTS} mapSDXMLStrWriterTest)
IF(NOT UNIX)
	ADD_TEST(mapSDXMLFileWriterTest ${MODULE_TESTS} mapSDXMLFileWriterTest ${TEMP} ${TEST_DATA_ROOT}/Core/XMLFileWriteReference.xml ${TEST_DATA_ROOT}/Core/XMLFileWriteReference_withXSLT.xml)
ENDIF(NOT UNIX)
ADD_TEST(mapModificationTimeValidatorTest ${MODULE_TESTS} mapModificationTimeValidatorTest)
