SET(CPP_FILES 
source/mapGenericImageReader.cpp
source/mapRegistrationFileReader.cpp
source/mapRegistrationKernelLoaderBase.cpp
source/mapRegistrationKernelLoadRequest.cpp
source/mapKernelLoaderLoadPolicy.cpp
)

SET(H_FILES 
include/mapExpandingFieldKernelWriter.h
include/mapExpandingFieldKernelLoader.h
include/mapMatrixModelBasedKernelWriter.h
include/mapMatrixModelBasedKernelLoader.h
include/mapNullRegistrationKernelLoader.h
include/mapNullRegistrationKernelWriter.h
include/mapRegistrationFileReader.h
include/mapRegistrationFileTags.h
include/mapRegistrationFileWriter.h
include/mapRegistrationKernelLoaderBase.h
include/mapRegistrationKernelWriterBase.h
include/mapRegistrationKernelWriteRequest.h
include/mapRegistrationKernelLoadRequest.h
include/mapKernelWriterLoadPolicy.h
include/mapKernelLoaderLoadPolicy.h
include/mapImageReader.h
include/mapImageWriter.h
include/mapGenericImageReader.h
)

SET(TPP_FILES
include/mapExpandingFieldKernelWriter.tpp
include/mapExpandingFieldKernelLoader.tpp
include/mapMatrixModelBasedKernelWriter.tpp
include/mapMatrixModelBasedKernelLoader.tpp
include/mapNullRegistrationKernelWriter.tpp
include/mapNullRegistrationKernelLoader.tpp
include/mapRegistrationFileWriter.tpp
include/mapRegistrationKernelWriterBase.tpp
include/mapRegistrationKernelWriteRequest.tpp
include/mapKernelWriterLoadPolicy.tpp
include/mapImageReader.tpp
include/mapImageWriter.tpp
)

SET(TEST_CPP_FILES
test/mapIOTests.cpp
test/mapMatrixModelBasedKernelWriterTest.cpp
test/mapMatrixModelBasedKernelLoaderTest.cpp
test/mapRegistrationFileWriterTest.cpp
test/mapRegistrationFileReaderTest.cpp
test/mapNullRegistrationKernelWriterTest.cpp
test/mapExpandingFieldKernelWriterTest.cpp
test/mapExpandingFieldKernelLoaderTest.cpp
)