# Usage: MAP_CHECK_ITK_REVIEW_ACTIVE(RESULT_VAR)
# check if for the used ITK the ITKReview Module is activated.
MACRO(MAP_CHECK_ITK_REVIEW_ACTIVE RESULT_VAR)

  SET(${RESULT_VAR} "OFF")
  IF(${ITK_VERSION} VERSION_LESS "4.5.2")
    IF(${ITK_USE_REVIEW})
      SET(${RESULT_VAR} "ON")
    ENDIF(${ITK_USE_REVIEW})
  ELSE(${ITK_VERSION} VERSION_LESS "4.5.2")
	SET(indexITKReview -1)
    LIST(FIND ITK_MODULES_ENABLED "ITKReview" indexITKReview)
	IF(NOT ${indexITKReview} EQUAL -1)
      SET(${RESULT_VAR} "ON")
	ENDIF(NOT ${indexITKReview} EQUAL -1)
  ENDIF(${ITK_VERSION} VERSION_LESS "4.5.2")

ENDMACRO(MAP_CHECK_ITK_REVIEW_ACTIVE)

